services:

  web:
    build: .
    container_name: db_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./www:/var/www/html"
    environment:
      ORA_USER: ${ORA_USER}
      ORA_PASS: ${ORA_PASS}
      ORA_HOST: ${ORA_HOST}
      ORA_PORT: ${ORA_PORT}
      ORA_SID:  ${ORA_SID}
